/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Christian Bauer
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_SpritesOn                           0
#define GD_SpriteCollisions                    1
#define GD_Joystick2On                         2
#define GD_JoystickSwap                        3
#define GD_LimitSpeed                          4
#define GD_FastReset                           5
#define GD_CIAIRQHack                          6
#define GD_SIDFilters                          7
#define GD_NormalCycles                        8
#define GD_BadLineCycles                       9
#define GD_CIACycles                           10
#define GD_FloppyCycles                        11
#define GD_SkipFrames                          12
#define GD_SIDType                             13
#define GD_REUSize                             14
#define GD_DrivePath8                          15
#define GD_DriveType8                          16
#define GD_DrivePath9                          17
#define GD_DriveType9                          18
#define GD_DrivePath10                         19
#define GD_DriveType10                         20
#define GD_DrivePath11                         21
#define GD_DriveType11                         22
#define GD_MapSlash                            23
#define GD_Emul1541Proc                        24
#define GD_OK                                  25
#define GD_Cancel                              26
#define GD_GetDrive8                           27
#define GD_GetDrive9                           28
#define GD_GetDrive10                          29
#define GD_GetDrive11                          30

#define GDX_SpritesOn                          0
#define GDX_SpriteCollisions                   1
#define GDX_Joystick2On                        2
#define GDX_JoystickSwap                       3
#define GDX_LimitSpeed                         4
#define GDX_FastReset                          5
#define GDX_CIAIRQHack                         6
#define GDX_SIDFilters                         7
#define GDX_NormalCycles                       8
#define GDX_BadLineCycles                      9
#define GDX_CIACycles                          10
#define GDX_FloppyCycles                       11
#define GDX_SkipFrames                         12
#define GDX_SIDType                            13
#define GDX_REUSize                            14
#define GDX_DrivePath8                         15
#define GDX_DriveType8                         16
#define GDX_DrivePath9                         17
#define GDX_DriveType9                         18
#define GDX_DrivePath10                        19
#define GDX_DriveType10                        20
#define GDX_DrivePath11                        21
#define GDX_DriveType11                        22
#define GDX_MapSlash                           23
#define GDX_Emul1541Proc                       24
#define GDX_OK                                 25
#define GDX_Cancel                             26
#define GDX_GetDrive8                          27
#define GDX_GetDrive9                          28
#define GDX_GetDrive10                         29
#define GDX_GetDrive11                         30

#define Prefs_CNT 31

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *PrefsWnd;
extern struct Gadget        *PrefsGList;
extern struct Menu          *PrefsMenus;
extern struct IntuiMessage   PrefsMsg;
extern UWORD                 PrefsZoom[4];
extern struct Gadget        *PrefsGadgets[31];
extern UWORD                 PrefsLeft;
extern UWORD                 PrefsTop;
extern UWORD                 PrefsWidth;
extern UWORD                 PrefsHeight;
extern UBYTE                *PrefsWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern UBYTE                *SIDType0Labels[];
extern UBYTE                *REUSize0Labels[];
extern UBYTE                *DriveType80Labels[];
extern UBYTE                *DriveType90Labels[];
extern UBYTE                *DriveType100Labels[];
extern UBYTE                *DriveType110Labels[];
extern struct IntuiText      PrefsIText[];
extern struct NewMenu        PrefsNewMenu[];
extern UWORD                 PrefsGTypes[];
extern struct NewGadget      PrefsNGad[];
extern ULONG                 PrefsGTags[];

extern int SpritesOnClicked( void );
extern int SpriteCollisionsClicked( void );
extern int Joystick2OnClicked( void );
extern int JoystickSwapClicked( void );
extern int LimitSpeedClicked( void );
extern int FastResetClicked( void );
extern int CIAIRQHackClicked( void );
extern int SIDFiltersClicked( void );
extern int NormalCyclesClicked( void );
extern int BadLineCyclesClicked( void );
extern int CIACyclesClicked( void );
extern int FloppyCyclesClicked( void );
extern int SkipFramesClicked( void );
extern int SIDTypeClicked( void );
extern int REUSizeClicked( void );
extern int DrivePath8Clicked( void );
extern int DriveType8Clicked( void );
extern int DrivePath9Clicked( void );
extern int DriveType9Clicked( void );
extern int DrivePath10Clicked( void );
extern int DriveType10Clicked( void );
extern int DrivePath11Clicked( void );
extern int DriveType11Clicked( void );
extern int MapSlashClicked( void );
extern int Emul1541ProcClicked( void );
extern int OKClicked( void );
extern int CancelClicked( void );
extern int GetDrive8Clicked( void );
extern int GetDrive9Clicked( void );
extern int GetDrive10Clicked( void );
extern int GetDrive11Clicked( void );
extern int PrefsOpen( void );
extern int PrefsSave( void );
extern int PrefsSaveAs( void );
extern int PrefsRevert( void );
extern int PrefsOK( void );
extern int PrefsCancel( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void PrefsRender( void );
extern int HandlePrefsIDCMP( void );
extern int PrefsVanillaKey();
extern int OpenPrefsWindow( void );
extern void ClosePrefsWindow( void );
